name: Release to PyPI
on:
  push:
    tags: ["*"]

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/platformdirs
    permissions:
      id-token: write
    steps:
      - name: Setup python to build package
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: setup uv for tox
        uses: yezz123/setup-uv@v4
      - name: Install build
        run: uv pip install build[uv] --system
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build package
        run: pyproject-build --installer uv --sdist --wheel . --outdir dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.1
